tarjetainventada= int(input("Inserte el numero de tarjeta inventada: "))
tarjetavisavigentecliente= int(input("Inserte el numero de tarjeta vigente: "))
numerocuenta= int(input("Inserte numero de cuenta: "))
numerosolicitud= int(input("Inserte numero de solicitud: "))
apellidoynombre= input("Apellido/Nombre: ")
DNI= int(input("Numero de DNI: "))
nacionalidad= input("Nacionaldidad en dos letras: ")
sexo= input("Masculino M o Femenino F: ")
estadocivil= int(input("1 soltero, 2 casado, 5 divorciado: "))
fechanacimiento= int(input("Fecha de nacimiento DDMMAA: "))
coddistribucion= int(input("Codigo de distribucion: "))
fechaactual= int(input("Fecha actual: "))

print(f"79044082           {tarjetainventada}79{numerocuenta}044082{numerosolicitud}{tarjetainventada}{apellidoynombre}")
print(f"I150SC")
print(f"DNI{DNI}{nacionalidad}{sexo}{estadocivil}{fechanacimiento}000008051")
print(f"100001000010000")
print(f"00240472863")
print(f"78")
print(f"{coddistribucion}")
print(f"CR0104")
print(f"N")
print(f"030140519300623")
print(f"BB")
print(f"00000000{tarjetavisavigentecliente}0000")
print(f"0190096720000")
print(f"{fechaactual}")
